fragment BuildForUseDownloadBuild on Build {
  id
  platform
  distribution
  artifacts {
    buildUrl
  }
  project {
    id
    slug
  }
}

fragment BuildForBuildsListItem on Build {
  id
  ...BuildForUseDownloadBuild
  activityTimestamp
  platform
  distribution
  status
  project {
    id
    name
  }
}

query GetAppBuilds($appId: String!, $offset: Int!, $limit: Int!) {
  app {
    byId(appId: $appId) {
      id
      name
      builds(limit: $limit, offset: $offset) {
        ...BuildForBuildsListItem
      }
    }
  }
}
