fragment ProjectForProjectsListItem on App {
  id
  name
  icon {
    url
  }
}

query GetAccountAppsAndBuilds($accountId: String!, $offset: Int!, $limit: Int!) {
  account {
    byId(accountId: $accountId) {
      id
      name
      apps(limit: $limit, offset: $offset, includeUnpublished: true) {
        id
        ...ProjectForProjectsListItem
      }
      builds(limit: 3, offset: 0, status: FINISHED) {
        id
        ...BuildForBuildsListItem
      }
    }
  }
}
