fragment Account on Account {
  id
  name
  owner {
    id
    username
    profilePhoto
    firstName
    fullName
    lastName
  }
}

fragment CurrentUserData on User {
  id
  username
  firstName
  profilePhoto
  accounts {
    ...Account
  }
}

query GetCurrentUser {
  viewer {
    ...CurrentUserData
  }
}
